tes3

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,10 +32,10 @@ jobs:
       - name: Show sonar-scanner version
         run: sonar-scanner --version  
 
-      - name: Check Sonar server connectivity
-        run: |
-        echo "Pinging Sonar host..."
-        curl -sSf "${{ secrets.SONAR_URL }}/api/server/version" || { echo "Cannot reach Sonar server"; exit 1;}
+     # - name: Check Sonar server connectivity
+      #  run: |
+       # echo "Pinging Sonar host..."
+        #curl -sSf "${{ secrets.SONAR_URL }}/api/server/version" || { echo "Cannot reach Sonar server"; exit 1;}
 
 
 
